import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { themeInitScript } from "@/lib/theme";
import ThemeToggle from "@/components/ui/ThemeToggle";
import Footer from "@/components/footer/Footer";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} app-body`}>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        {children}
        <Footer />
        <div className="theme-toggle-fixed">
          <ThemeToggle />
        </div>
      </body>
    </html>
  );
}